name: Pages

on:
  push:
    branches:
      - source  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Set npm registry to official
        run: npm config set registry https://registry.npmjs.org/

    #   - name: Cache NPM dependencies
    #     uses: actions/cache@v3
    #     with:
    #       path: |
    #         ~/.npm
    #         node_modules
    #       key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
    #       restore-keys: |
    #         ${{ runner.os }}-npm-
      - name: Clean install directories
        run: |
            rm -rf node_modules
            npm cache clean --force
      - name: Use stable npm version
        run: npm install -g npm@8.19.4

      - name: Install Hexo CLI
        run: npm install -g hexo-cli

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
